// Game variables
let MINIMUM_PLAYER_COUNT = 3;
let TURN_TIME_LIMIT = 60;
let PRE_GAME_TIME = 5;
let POST_GAME_TIME = 20;

// Faction variables
let TRAITOR_FRACTION = 0.3;
let DETECTIVE_FRACTION = 0.1;

module.exports = {
    MINIMUM_PLAYER_COUNT,
    TURN_TIME_LIMIT,
    PRE_GAME_TIME,
    POST_GAME_TIME,

    TRAITOR_FRACTION,
    DETECTIVE_FRACTION
}
